version: '3.7'

services:
  web:
    image: extend-api-service:latest
    container_name: deploy_web
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    container_name: deploy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hello

  nginx:
    build: ./nginx
    container_name: deploy_nginx
    ports:
      - 8008:80
    depends_on:
      - web

volumes:
  postgres_data:
